# Write your MySQL query statement below
SELECT A.NAME,SUM(
CASE
WHEN A.ID=B.USER_ID THEN B.DISTANCE
ELSE 0
END
) AS TRAVELLED_DISTANCE FROM USERS A,RIDES B
GROUP BY A.ID
ORDER BY TRAVELLED_DISTANCE DESC,NAME ASC