# Write your MySQL query statement below
SELECT USER_ID AS BUYER_ID,JOIN_DATE,
COUNT(O.BUYER_ID) AS ORDERS_IN_2019 FROM USERS U
LEFT JOIN ORDERS O ON U.USER_ID=O.BUYER_ID AND YEAR(ORDER_DATE)='2019' 
GROUP BY USER_ID
ORDER BY USER_ID